#!/usr/bin/env python
"""
Interactive presentation with Bokeh

Run from the project root with:   bokeh serve --show app
Then open:                        http://localhost:5006/app
(Requires Bokeh 3.7 or later, see requirements.txt.)

Data: data/master_governance_dataset.csv (generated by notebooks/2_create_dataset.ipynb).

=== BOKEH SERVER ARCHITECTURE ===
A Bokeh server keeps a websocket connection between Python and the browser:
widget callbacks written in Python run on the SERVER, and the changes are pushed to the browser.
The whole application is a class that builds the slides once, then swaps the visible slide.

=== ONE RULE FOR EVERY GRAPH ===
"The higher the score / the higher the position, the more corrupt."

=== NAMING CONVENTIONS ===
- Data columns are lower_snake_case and named after what they hold:
    country, regime, region, year, cpi, gdp_per_capita             (from the CSV, renamed in load_data)
    corruption_score  = PCI x 100, THE corruption measure of slides 2 to 6 (0 = cleanest, 100 = most corrupt)
    perception_score  = 100 - CPI, the perception-based measure of slide 2 (higher = more corrupt)
    regime_median     = median corruption_score of the country's own regime
    deviation         = corruption_score - regime_median                  (positive = more corrupt than typical)
- Chart columns for marker styling: marker_shape, marker_size, outline_color, outline_width.
- Constants are UPPER_CASE and spell out their meaning (e.g. FRAME_WIDTH, SELECTED_COUNTRIES).

=== SHARED DATA ===
The latest-year frame (with regime median and deviation), the rank correlations with wealth and the
persistence of the biggest exceptions are computed ONCE in `InteractivePresentation.__init__`
and reused by every slide that needs them.

=== GLOBAL ACCESSIBILITY SETTINGS ===
Two settings live in the header menu and apply to every slide, whichever slide is open:
  - colour-blind mode: one marker shape per regime + dark outlines (slides 2, 3 and 4)
  - accessible text: a legible font with more spacing (all text, axes, labels, buttons)
Slides do not know about the menu. Instead, every marker source is created with
`InteractivePresentation._marker_source`, which registers a small function in `self._color_blind_listeners`;
when the setting changes, the app calls them all (even for hidden slides), so the choice is still there
when the person navigates. Every chart and label set is registered the same way for the font setting.
"""

from pathlib import Path

import numpy as np
import pandas as pd
from bokeh.layouts import column, row
from bokeh.models import (
    AdaptiveTicker,
    Button,
    CheckboxGroup,
    ColumnDataSource,
    CustomJS,
    Div,
    Dropdown,
    HoverTool,
    InlineStyleSheet,
    LabelSet,
    LinearAxis,
    NumeralTickFormatter,
    Range1d,
    TapTool,
)
from bokeh.plotting import curdoc, figure
from bokeh.transform import factor_cmap

# =============================================================================
# SETTINGS
# =============================================================================
DATA_PATH = Path(__file__).resolve().parent.parent / "data" / "master_governance_dataset.csv"
LATEST_YEAR = 2024  # last year with CPI data
PERSISTENCE_BASE_YEAR = 2012  # slides 5 and 6: were today's biggest exceptions already exceptions then?
EXCEPTIONS_PER_SIDE = 10  # biggest exceptions kept on each side of the regime median

APP_TITLE = "Corruption, Regimes and Wealth"
APP_SUBTITLE = "If political systems dictate corruption, why do autocracies and democracies overlap?"
SLIDE_TITLES = [
    "Intro",
    "Measures of corruption",
    "Who breaks the pattern?",
    "Does wealth matter?",
    "Do exceptions last?",
    "Conclusions",
]

# Regimes are ordered (closed autocracy -> liberal democracy), so the colours are ordered too:
# warm = autocracy, cool = democracy (colour-blind safe, Okabe-Ito palette).
REGIMES = ["Closed autocracy", "Electoral autocracy", "Electoral democracy", "Liberal democracy"]
REGIME_COLORS = ["#D55E00", "#E69F00", "#56B4E9", "#0072B2"]
REGIME_COLOR_BY_NAME = dict(zip(REGIMES, REGIME_COLORS))
# Shapes are only used when colour-blind mode is on (header menu)
REGIME_SHAPES = dict(zip(REGIMES, ["square", "triangle", "circle", "diamond"]))
# Same shapes as text symbols, for the glossary
SHAPE_GLYPHS = {"square": "■", "triangle": "▲", "circle": "●", "diamond": "◆"}

# Definitions follow V-Dem's "Regimes of the World"
REGIME_DEFINITIONS = {
    "Closed autocracy": "No multi-party elections for the head of state or the parliament.",
    "Electoral autocracy": "Several parties can run, but elections are not free and fair, "
    "so those in power are hard to remove.",
    "Electoral democracy": "Free and fair multi-party elections, with freedom of speech and association.",
    "Liberal democracy": "An electoral democracy where courts, parliament and the law also "
    "keep those in power in check.",
}

# --- Layout: header, tabs, slide container and every slide share this exact width -----------------
FRAME_WIDTH, FRAME_HEIGHT = 1060, 700  # FRAME_HEIGHT is a minimum: the page grows if a slide needs more room
SIDE_PANEL_WIDTH = 320  # text panel next to a chart (slides 2 and 3)
PLOT_WIDTH = FRAME_WIDTH - SIDE_PANEL_WIDTH  # chart + text panel = FRAME_WIDTH
SIDE_TEXT_LAYOUT = {"width": SIDE_PANEL_WIDTH - 20, "margin": (0, 0, 0, 20)}  # text blocks in the side panel

# Header controls: sizes in pixels (the banner row is sized from them)
HEADER_CONTROL_HEIGHT = 34
MENU_BUTTON_WIDTH, MENU_BUTTON_MARGIN_RIGHT = 150, 12
ARROW_BUTTON_WIDTH, ARROW_BUTTON_MARGIN_X = 38, 4
PAGE_COUNTER_WIDTH = 52
HEADER_CONTROLS_WIDTH = (
    MENU_BUTTON_WIDTH + MENU_BUTTON_MARGIN_RIGHT
    + 2 * (ARROW_BUTTON_WIDTH + 2 * ARROW_BUTTON_MARGIN_X)
    + PAGE_COUNTER_WIDTH
)

# --- Accessibility: text mode ---------------------------------------------------------------------
# Fonts must be installed on the viewer's computer; the list falls back to Verdana, which is on
# nearly every Windows / macOS machine and was designed for legibility on screen.
ACCESSIBLE_FONT = '"Atkinson Hyperlegible", "OpenDyslexic", Verdana, "Trebuchet MS", sans-serif'
DEFAULT_PLOT_FONT = "helvetica"  # Bokeh's default for text drawn on the charts
# CSS injected into every Div / button / chart (their text lives in separate "shadow DOMs",
# so the style has to be added to each of them; they all share ONE stylesheet object).
ACCESSIBLE_CSS = f"""
:host, * {{
    font-family: {ACCESSIBLE_FONT} !important;
    letter-spacing: 0.04em !important;
    word-spacing: 0.1em !important;
}}
div, p, li, td, th, label, span {{ line-height: 1.6 !important; }}
button, .bk-btn {{ line-height: 1.25 !important; }}
"""

REQUIRED_COLUMNS = {"entity", "year", "CPI", "PCI", "regime_label", "region", "GDP_pc"}
# CSV column -> name used everywhere in this file (PCI is turned into corruption_score in load_data)
COLUMN_NAMES = {
    "entity": "country",
    "regime_label": "regime",
    "CPI": "cpi",
    "PCI": "pci",
    "GDP_pc": "gdp_per_capita",
}

# --- Axis labels -----------------------------------------------------------------------------------
CORRUPTION_AXIS_LABEL = "Corruption score (PCI x 100)"  # tall charts (slide 3)
CORRUPTION_AXIS_LABEL_SHORT = "Corruption score"  # small panels (slides 4 and 5)
SCATTER_X_AXIS_LABEL = "Experts: corruption score (PCI x 100)"
SCATTER_Y_AXIS_LABEL = "Perception: 100 - Corruption Perceptions Index"

SCATTER_TAKEAWAY_HTML = """
<div style="font-size:16px; color:#1b2a41; margin:0; padding:0; line-height:1.4;">
    <b>Key takeaway:</b> Public perception and country experts strongly agree on corruption levels, yet regimes naturally sort from cleanest to most corrupt.
</div>
"""

SCATTER_NOTE_HTML = """
    <br>
    <b>Two ways to measure:</b><br>
    • <b>Perception (CPI — Transparency International):</b> Business executives say how widespread they think bribery and corruption are in the public sector.<br>
    • <b>Experts (PCI — V-Dem Institute):</b> Country experts evaluate actual theft of public money and abuse of power across government branches.<br><br>
    <b>Reading the line:</b> On the dashed line, both measures agree. Clean democracies float slightly above because people rarely rate a country as completely corruption-free, whereas expert scores can reach zero.
"""

# --- Slides 3 to 6: exceptions to the regime pattern ---------------------------------------------------------------------------------------
LARGE_DEVIATION_THRESHOLD = 25  # "far from the typical level" = more than 25 points from the median of its regime
LABEL_OFFSET = (9, -5)  # slide 3: where each name is written, relative to its dot (right of the dot)

# Countries named on slides 3 and 4 (the only names shown) and followed over time on slide 5
SELECTED_COUNTRIES = ["Georgia", "Hungary", "Brazil", "Eswatini", "Singapore", "Italy"]
TIMESERIES_FIRST_YEAR = 1979  # slide 5 starts here
TIMESERIES_COLUMNS = 3  # slide 5: panels per row
GDP_LINE_COLOR = "#2b4162"  # slide 5: GDP per capita line and right axis (not used by any regime)
# Slide 4: a label whose dot is further right than this share of the x axis is written LEFT of the dot,
# so that it never runs out of the plot (e.g. Singapore, the richest country)
LABEL_FLIP_SHARE = 0.75


# =============================================================================
# DATA PREPARATION (plain pandas, no Bokeh)
# =============================================================================
def load_data(path=DATA_PATH):
    """Read the master dataset, check its columns, rename them and derive corruption_score = PCI x 100."""
    data = pd.read_csv(path)
    missing = REQUIRED_COLUMNS - set(data.columns)
    if missing:
        raise ValueError(
            f"Missing columns {sorted(missing)} in {path}. "
            "Re-generate the file with notebooks/2_create_dataset.ipynb."
        )
    data = data.rename(columns=COLUMN_NAMES)
    data["corruption_score"] = data.pop("pci") * 100  # PCI: 0-1, 1 = corrupt, so just rescale it
    return data


def build_year_frame(data, year):
    """One row per country for the chosen year, with every measure oriented 'higher = more corrupt'.

    Adds perception_score (100 - CPI), regime_median and deviation
    (corruption score minus the median of the country's own regime). Rows are ordered by regime, then country."""
    frame = data[data["year"] == year].dropna(subset=["cpi", "corruption_score", "regime"])
    frame = frame[frame["regime"].isin(REGIMES)].copy()
    frame["regime"] = pd.Categorical(frame["regime"], categories=REGIMES, ordered=True)
    frame = frame.sort_values(["regime", "country"]).reset_index(drop=True)
    frame["regime"] = frame["regime"].astype(str)
    frame["region"] = frame["region"].fillna("")

    frame["perception_score"] = 100 - frame["cpi"]  # CPI: 100 = clean, so flip it
    frame["regime_median"] = frame.groupby("regime")["corruption_score"].transform("median")
    frame["deviation"] = frame["corruption_score"] - frame["regime_median"]
    return frame


def marker_style_columns(regimes, color_blind, base_size):
    """Marker shape, outline and size of every point (slides 2, 3 and 4).
    Default: same circle for everyone (colour only).
    Colour-blind mode: one shape per regime, a dark and thicker outline, and slightly bigger markers."""
    regimes = list(regimes)
    n = len(regimes)
    if color_blind:
        return {
            "marker_shape": [REGIME_SHAPES[r] for r in regimes],
            "outline_color": ["#111111"] * n,  # dark edge keeps overlapping points apart
            "outline_width": [1.8] * n,
            "marker_size": [base_size + 2] * n,
        }
    return {
        "marker_shape": ["circle"] * n,
        "outline_color": ["white"] * n,
        "outline_width": [1] * n,
        "marker_size": [base_size] * n,
    }


def scatter_summary_html(frame):
    """Small text block: overall correlation between perception and experts."""
    correlation = frame["corruption_score"].corr(frame["perception_score"])
    return f"""
    <div style="font-size:14px; line-height:1.4;">
        <b>Correlation:</b> {correlation:.2f} (1 = perfect agreement)<br>
        <span style="color:#555; font-size:12px;">
            Both measures show strong global consensus, but look at the public sector from two distinct angles.
        </span>
    </div>
    """


def regime_glossary_html(color_blind=False):
    """Glossary of the four regimes. The symbol in front matches the markers of the charts."""
    items = "".join(
        f"<li style='margin-bottom: 8px;'><span style='color:{color}'>"
        f"{SHAPE_GLYPHS[REGIME_SHAPES[name]] if color_blind else SHAPE_GLYPHS['circle']}"
        f"</span> <b>{name}</b>: {REGIME_DEFINITIONS[name]}</li>"
        for name, color in REGIME_COLOR_BY_NAME.items()
    )
    return f"""
    <div style="font-size: 14px; line-height: 1.55; color: #222;">
        <div style="font-weight: bold; margin: 12px 0 10px 0;">What do the regimes mean?</div>
        <ul style="margin: 0; padding-left: 18px; list-style: none;">{items}</ul>
    </div>
    """


# ---------------------------- Helpers for slides 3 to 6 -------------------------------
def wealth_correlation_by_regime(frame):
    """Rank correlation between GDP per capita and corruption score, inside each regime."""
    stats = {}
    for regime in REGIMES:
        in_regime = frame[frame["regime"] == regime]
        with_gdp = in_regime.dropna(subset=["gdp_per_capita"])
        if len(with_gdp) >= 5:
            # Spearman = Pearson correlation of the ranks (done by hand so that scipy is not required)
            rank_corr = with_gdp["gdp_per_capita"].rank().corr(with_gdp["corruption_score"].rank())
        else:
            rank_corr = np.nan
        stats[regime] = {
            "rank_corr": rank_corr,
            "n_countries": len(with_gdp),
            "n_missing": len(in_regime) - len(with_gdp),
        }
    return stats


def count_persistent_exceptions(current_frame, earlier_frame, n_per_side=EXCEPTIONS_PER_SIDE):
    """Among the biggest exceptions on each side now, how many were already on the same side earlier?
    Returns (number on the same side, number of exceptions compared)."""
    earlier = earlier_frame.set_index("country")["deviation"]
    exceptions = pd.concat(
        [current_frame.nlargest(n_per_side, "deviation"), current_frame.nsmallest(n_per_side, "deviation")]
    ).drop_duplicates("country")
    exceptions = exceptions[exceptions["country"].isin(earlier.index)]
    same_side = np.sign(exceptions["deviation"].to_numpy()) == np.sign(earlier.loc[exceptions["country"]].to_numpy())
    return int(same_side.sum()), len(exceptions)


def build_regime_distribution(frame):
    """Slide 3: box statistics, one jittered dot per country, and the dots to be named.
    Works on the shared latest-year frame; the score is the corruption score (higher = more corrupt)."""
    position_of_regime = {regime: i for i, regime in enumerate(REGIMES)}

    grouped = frame.groupby("regime")["corruption_score"]
    quartiles = grouped.quantile([0.25, 0.5, 0.75]).unstack().reindex(REGIMES)
    counts = grouped.size().reindex(REGIMES).fillna(0).astype(int)
    box_columns = {
        "x_position": list(position_of_regime.values()),
        "q1": quartiles[0.25].tolist(),
        "median": quartiles[0.5].tolist(),
        "q3": quartiles[0.75].tolist(),
        "regime_color": list(REGIME_COLORS),
        "tick_label": [f"{regime} ({counts[regime]})" for regime in REGIMES],
    }

    rng = np.random.default_rng(7)  # fixed seed: the dots do not move at every reload
    points = frame[["country", "regime", "region", "corruption_score"]].assign(
        x_position=frame["regime"].map(position_of_regime) + rng.uniform(-0.22, 0.22, len(frame)),
        regime_color=frame["regime"].map(REGIME_COLOR_BY_NAME),
    )
    labelled = points[points["country"].isin(SELECTED_COUNTRIES)]
    return box_columns, points.to_dict("list"), labelled.to_dict("list")


def build_timeseries(data, country, first_year=TIMESERIES_FIRST_YEAR):
    """Corruption score and GDP per capita of one country from first_year onwards, plus the background bands
    (one per run of years spent in the same regime). A band spans from half a year before its first year to
    half a year after its last year, so that consecutive bands touch."""
    history = (
        data[(data["country"] == country) & (data["year"] >= first_year)]
        .dropna(subset=["corruption_score"])
        .sort_values("year")
    )
    line = {
        "year": history["year"].tolist(),
        "corruption_score": history["corruption_score"].tolist(),
        "gdp_per_capita": history["gdp_per_capita"].tolist(),  # NaN where missing: the line simply has a gap
        "regime": history["regime"].astype(str).tolist(),
    }

    bands = {"left": [], "right": [], "regime_color": [], "regime": []}

    def close_band(first, last, regime):
        bands["left"].append(first - 0.5)
        bands["right"].append(last + 0.5)
        bands["regime_color"].append(REGIME_COLOR_BY_NAME[regime])
        bands["regime"].append(regime)

    run_first_year = run_regime = previous_year = None
    for year, regime in zip(history["year"], history["regime"]):
        regime = regime if regime in REGIME_COLOR_BY_NAME else None
        if regime != run_regime or (previous_year is not None and year != previous_year + 1):
            if run_regime is not None:
                close_band(run_first_year, previous_year, run_regime)
            run_first_year, run_regime = year, regime
        previous_year = year
    if run_regime is not None:
        close_band(run_first_year, previous_year, run_regime)
    return line, bands


def set_plot_font(plot, family):
    """Change the font of the text drawn on a chart (title, axes, legend)."""
    plot.title.text_font = family
    for axis in list(plot.xaxis) + list(plot.yaxis):
        axis.axis_label_text_font = family
        axis.major_label_text_font = family
    for legend in plot.legend:
        legend.label_text_font = family
        legend.title_text_font = family


def checkbox_mark(on):
    return "☑" if on else "☐"


# =============================================================================
# THE APPLICATION
# =============================================================================
class InteractivePresentation:
    """
    Main application class.

    Bokeh application pattern:
    1. Initialize state and shared data
    2. Create the slides
    3. Create the navigation / header
    4. Compose the layout
    5. Add it to the document
    """

    def __init__(self):
        # State is kept on the server and persists across callbacks
        self.data = load_data()
        self.total_slides = len(SLIDE_TITLES)
        self.current_slide = 0

        # Shared data, computed once and reused by every slide
        self.latest_frame = build_year_frame(self.data, LATEST_YEAR)
        self.wealth_stats = wealth_correlation_by_regime(self.latest_frame)
        self.n_persistent, self.n_exceptions = count_persistent_exceptions(
            self.latest_frame, build_year_frame(self.data, PERSISTENCE_BASE_YEAR)
        )

        # Global accessibility settings (apply to every slide)
        self.accessibility = {"color_blind": False, "font": False}
        self.accessibility_stylesheet = InlineStyleSheet(css="")  # empty = normal text; ACCESSIBLE_CSS = accessible text
        self._color_blind_listeners = []  # functions(color_blind: bool), registered by the slides
        self._plots, self._label_sets = [], []  # everything whose font must change in text mode

        # Order matters: slides first, then navigation (needs the titles), then layout
        self.slides = self.create_slides()
        self.create_navigation()
        self.create_layout()

    # -------------------------------------------------------------------------
    # Small factories: every element gets the shared accessibility stylesheet / registration
    # -------------------------------------------------------------------------
    def _div(self, text, **kwargs):
        return Div(text=text, stylesheets=[self.accessibility_stylesheet], **kwargs)

    def _heading(self, slide_number):
        return self._div(
            text=f"<h2 style='margin:4; padding:0; color:#1b2a41; line-height:1.2;'>{SLIDE_TITLES[slide_number - 1]}</h2>",
            width=FRAME_WIDTH,
            margin=(0, 0, 4, 0),  # Only 4px under the title
        )

    def _figure(self, **kwargs):
        """Chart without the toolbar (the small buttons next to the plot) and without pan / zoom tools."""
        kwargs.setdefault("toolbar_location", None)
        kwargs.setdefault("tools", "")
        plot = figure(stylesheets=[self.accessibility_stylesheet], **kwargs)
        self._plots.append(plot)
        return plot

    def _label_set(self, **kwargs):
        label_set = LabelSet(**kwargs)
        self._label_sets.append(label_set)
        return label_set

    def _marker_source(self, columns, regimes, base_size):
        """Data source whose marker style follows the global colour-blind mode (now and on every change)."""
        regimes = list(regimes)
        source = ColumnDataSource(
            data={**columns, **marker_style_columns(regimes, self.accessibility["color_blind"], base_size)}
        )

        def update_markers(color_blind):
            source.data = {**source.data, **marker_style_columns(regimes, color_blind, base_size)}

        self._color_blind_listeners.append(update_markers)
        return source

    # -------------------------------------------------------------------------
    # Global accessibility settings
    # -------------------------------------------------------------------------
    def set_color_blind(self, on):
        self.accessibility["color_blind"] = on
        for update in self._color_blind_listeners:
            update(on)

    def set_accessible_font(self, on):
        self.accessibility["font"] = on
        self.accessibility_stylesheet.css = ACCESSIBLE_CSS if on else ""  # buttons, text blocks, tooltips
        family = ACCESSIBLE_FONT if on else DEFAULT_PLOT_FONT
        for plot in self._plots:  # text drawn on the charts
            set_plot_font(plot, family)
        for label_set in self._label_sets:
            label_set.text_font = family

    def _accessibility_menu_items(self):
        return [
            (f"{checkbox_mark(self.accessibility['color_blind'])}  Colour-blind mode (shapes + outlines)",
             "color_blind"),
            (f"{checkbox_mark(self.accessibility['font'])}  Accessible text (legible font, more spacing)", "font"),
        ]

    def _refresh_accessibility_menu(self):
        n_on = sum(self.accessibility.values())
        self.accessibility_menu.label = "Accessibility" + (f" ({n_on})" if n_on else "")
        self.accessibility_menu.menu = self._accessibility_menu_items()

    def _on_accessibility_menu(self, event):
        if event.item == "color_blind":
            self.set_color_blind(not self.accessibility["color_blind"])
        elif event.item == "font":
            self.set_accessible_font(not self.accessibility["font"])
        self._refresh_accessibility_menu()

    # -------------------------------------------------------------------------
    # Navigation and header
    # -------------------------------------------------------------------------
    def create_navigation(self):
        """Tabs (one per slide), previous / next buttons and the accessibility menu."""
        tab_stylesheet = InlineStyleSheet(css="""
            .bk-btn {
                background: transparent; color: #5b6b7a; border: none; border-radius: 0;
                border-bottom: 3px solid transparent; box-shadow: none;
                font-size: 12px; padding: 6px 8px; white-space: normal; transition: all .15s;
            }
            .bk-btn:hover { background: #eef3f8; color: #1b2a41; }
            :host(.tab-active) .bk-btn {
                color: #0072B2; font-weight: 600; border-bottom: 3px solid #0072B2; background: #eef6fc;
            }
        """)
        # Widths add up to exactly FRAME_WIDTH (the first buttons get the remaining pixels)
        base_width, extra_pixels = divmod(FRAME_WIDTH, self.total_slides)
        self.tab_buttons = []
        for i, title in enumerate(SLIDE_TITLES):
            button = Button(label=f"{i + 1}. {title}", button_type="default", height=48,
                            width=base_width + (1 if i < extra_pixels else 0), margin=0,
                            stylesheets=[tab_stylesheet, self.accessibility_stylesheet])
            button.on_click(lambda i=i: self.go_to(i))
            self.tab_buttons.append(button)

        # Header controls (on the dark banner: light buttons)
        header_button_stylesheet = InlineStyleSheet(css="""
            .bk-btn {
                background: rgba(255,255,255,.12); color: white; border: 1px solid rgba(255,255,255,.4);
                border-radius: 6px; box-shadow: none; font-size: 13px; padding: 0 8px;
            }
            .bk-btn:hover { background: rgba(255,255,255,.25); color: white; }
            .bk-btn:focus-visible { outline: 3px solid #ffffff; outline-offset: 2px; }
            .bk-btn:disabled { opacity: .35; background: transparent; cursor: default; }
        """)
        arrow_stylesheet = InlineStyleSheet(css=".bk-btn { font-size: 20px; padding: 0 0 3px 0; }")

        def make_arrow(label, callback):
            button = Button(
                label=label, width=ARROW_BUTTON_WIDTH, height=HEADER_CONTROL_HEIGHT,
                margin=(0, ARROW_BUTTON_MARGIN_X, 0, ARROW_BUTTON_MARGIN_X),
                stylesheets=[header_button_stylesheet, arrow_stylesheet, self.accessibility_stylesheet],
            )
            button.on_click(callback)
            return button

        self.prev_button = make_arrow("‹", self.prev_slide)
        self.next_button = make_arrow("›", self.next_slide)
        # Slide counter: the box is a flex container, so the text sits exactly in the middle of the
        # space between the two arrows (horizontally and vertically)
        self.page_counter = self._div(
            text=self.get_page_counter_html(), width=PAGE_COUNTER_WIDTH, height=HEADER_CONTROL_HEIGHT, margin=0,
            styles={"display": "flex", "align-items": "center", "justify-content": "center"},
        )

        self.accessibility_menu = Dropdown(
            label="Accessibility", menu=self._accessibility_menu_items(), width=MENU_BUTTON_WIDTH,
            height=HEADER_CONTROL_HEIGHT, margin=(0, MENU_BUTTON_MARGIN_RIGHT, 0, 0),
            stylesheets=[header_button_stylesheet, self.accessibility_stylesheet],
        )
        self.accessibility_menu.on_event("menu_item_click", self._on_accessibility_menu)
        self._refresh_tabs()

    def get_page_counter_html(self):
        """Slide counter, between the two arrows. Line height and letter spacing are fixed (even in
        accessible-text mode) so that the number stays centred."""
        return (
            "<span style='font-size:12px; color:white; opacity:.85; white-space:nowrap; "
            "line-height:1 !important; letter-spacing:0 !important; word-spacing:0 !important;'>"
            f"{self.current_slide + 1} / {self.total_slides}</span>"
        )

    def create_header(self):
        """Row 1 of the banner: title + subtitle on the left; accessibility menu and < > on the right."""
        title = self._div(
            text=f"""
            <div style="color:white;">
                <div style="font-size:19px; font-weight:600;">{APP_TITLE}</div>
                <div style="font-size:12px; opacity:.8; margin-top:3px;">{APP_SUBTITLE}</div>
            </div>
            """,
            sizing_mode="stretch_width",
        )
        controls = row(self.accessibility_menu, self.prev_button, self.page_counter, self.next_button,
                       width=HEADER_CONTROLS_WIDTH, height=HEADER_CONTROL_HEIGHT, align="center")
        return row(
            title, controls, width=FRAME_WIDTH, margin=(0, 0, 6, 0),
            styles={
                "background": "linear-gradient(120deg,#1b2a41 0%,#324a5f 55%,#0072B2 100%)",
                "border-radius": "10px", "box-shadow": "0 2px 8px rgba(0,0,0,.15)",
                "padding": "10px 16px", "box-sizing": "border-box", "align-items": "center",
                "min-height": "66px",
            },
        )

    def _refresh_tabs(self):
        for i, button in enumerate(self.tab_buttons):
            button.css_classes = ["tab-active"] if i == self.current_slide else []
        self.prev_button.disabled = self.current_slide == 0
        self.next_button.disabled = self.current_slide == self.total_slides - 1

    def create_layout(self):
        """Row 1 (header) / row 2 (tabs) / slide: all FRAME_WIDTH wide. Then register in the document."""
        self.slide_container = column(
            self.slides[self.current_slide], width=FRAME_WIDTH, styles={"min-height": f"{FRAME_HEIGHT}px"}
        )
        tabs = row(*self.tab_buttons, width=FRAME_WIDTH, styles={"border-bottom": "1px solid #dde3ea"})
        self.main_layout = column(
            self.create_header(), tabs, self.slide_container,
            width=FRAME_WIDTH, margin=(10, 20, 10, 20),
        )
        curdoc().add_root(self.main_layout)
        curdoc().title = APP_TITLE

    def update_slide_view(self):
        """Show the current slide and refresh the tabs and the counter."""
        self.slide_container.children = [self.slides[self.current_slide]]
        self.page_counter.text = self.get_page_counter_html()
        self._refresh_tabs()

    def go_to(self, index):
        self.current_slide = index
        self.update_slide_view()

    def prev_slide(self):
        if self.current_slide > 0:
            self.go_to(self.current_slide - 1)

    def next_slide(self):
        if self.current_slide < self.total_slides - 1:
            self.go_to(self.current_slide + 1)

    # -------------------------------------------------------------------------
    # Slides
    # -------------------------------------------------------------------------
    def create_slides(self):
        return [
            self.create_slide_1_welcome(),
            self.create_slide_2_scatter(),
            self.create_slide_3_regime_distribution(),
            self.create_slide_4_wealth(),
            self.create_slide_5_timeseries(),
            self.create_slide_6_conclusions(),
        ]

    def create_slide_1_welcome(self):
        """Slide 1: title, research question, and presentation roadmap."""
        return self._div(
            text=f"""
            <div style="display: flex; justify-content: center; width: {FRAME_WIDTH}px;">
            <div style="width: 100%; max-width: 820px; margin: 40px 0 0 0; text-align: center; color: #1b2a41;">
                <h1 style="font-size: 34px; font-weight: 700; margin-bottom: 12px; color: #1b2a41;">
                    {APP_TITLE}
                </h1>
                <p style="font-size: 19px; color: #4a5568; line-height: 1.5; margin-bottom: 8px;">
                    {APP_SUBTITLE}
                </p>
                <div style="font-size: 13px; color: #718096; margin-bottom: 35px;">
                    {len(self.latest_frame)} countries analyzed ({LATEST_YEAR}) · Data curated by Our World in Data (OWID)
                </div>

                <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 24px; text-align: left; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05);">
                    <div style="font-size: 15px; font-weight: 600; margin-bottom: 12px; color: #0072B2;">
                        What this investigation explores:
                    </div>
                    <ul style="font-size: 14px; line-height: 1.7; margin: 0; padding-left: 20px; color: #334155;">
                        <li><b>Measuring corruption:</b> How perception surveys (CPI) compare with expert evaluations (PCI).</li>
                        <li><b>Regime baselines:</b> Why democracies aren't always clean and autocracies aren't uniformly corrupt.</li>
                        <li><b>The role of wealth:</b> Does GDP explain why certain nations defy expectations?</li>
                        <li><b>Historical stickiness:</b> Whether institutional outliers correct themselves or persist over decades.</li>
                    </ul>
                </div>

                <div style="margin-top: 30px; font-size: 13px; color: #64748b;">
                    Use the tabs above or the <b>‹</b> and <b>›</b> buttons to navigate through the findings.
                </div>
            </div>
            </div>
            """,
            width=FRAME_WIDTH,
        )

    def create_slide_2_scatter(self):
        """Slide 2: perceived corruption (CPI) vs expert-rated corruption score (PCI x 100), coloured by regime."""
        frame = self.latest_frame
        source = self._marker_source(
            frame[["country", "regime", "corruption_score", "perception_score"]].to_dict("list"),
            frame["regime"],
            base_size=11,
        )

        plot = self._figure(
            width=PLOT_WIDTH,
            height=560,
            title=f"Do the two corruption indexes agree? ({LATEST_YEAR})",
            x_range=(-2, 102),
            y_range=(-2, 102),
            x_axis_label=SCATTER_X_AXIS_LABEL,
            y_axis_label=SCATTER_Y_AXIS_LABEL,
        )

        # Dashed line: both indexes give exactly the same value
        plot.line(x=[0, 100], y=[0, 100], color="gray", line_dash="dashed", alpha=0.7)

        color_mapper = factor_cmap("regime", palette=REGIME_COLORS, factors=REGIMES)
        dots = plot.scatter(
            x="corruption_score",
            y="perception_score",
            source=source,
            size="marker_size",
            alpha=0.85,
            marker="marker_shape",  # column of the data: "circle" for all, or one shape per regime
            color=color_mapper,
            line_color="outline_color",  # column of the data: white edge, or dark edge
            line_width="outline_width",
            selection_color=color_mapper,
            nonselection_color=color_mapper,
            nonselection_alpha=0.1,
            legend_group="regime",
        )

        # Click on a point -> select every country of the same regime
        plot.add_tools(TapTool(renderers=[dots]))
        source.selected.js_on_change(
            "indices",
            CustomJS(
                args=dict(source=source),
                code="""
                const selected = cb_obj.indices;
                if (selected.length === 0) return;

                const regime = source.data['regime'][selected[0]];
                const all_regimes = source.data['regime'];
                const same_regime = [];
                for (let i = 0; i < all_regimes.length; i++) {
                    if (all_regimes[i] === regime) { same_regime.push(i); }
                }
                if (selected.length !== same_regime.length) { cb_obj.indices = same_regime; }
                """,
            ),
        )

        plot.add_tools(
            HoverTool(
                renderers=[dots],
                tooltips=[
                    ("Country", "@country"),
                    ("Regime", "@regime"),
                    ("Perception score (100 - CPI)", "@perception_score{0}"),
                    ("Corruption score (PCI x 100)", "@corruption_score{0}"),
                ],
            )
        )

        plot.legend.title = "Regime"
        plot.legend.location = "bottom_right"  # the empty corner of the plot

        # Click on a legend entry -> same effect as clicking a dot of that regime: select every country of the
        # regime. The legend's own click_policy is left at "none" (the default) so nothing is hidden or muted.
        # (The legend_item_click event needs a recent Bokeh, 3.7 or later.)
        plot.legend[0].js_on_click(
            CustomJS(
                args=dict(source=source),
                code="""
                const regime = cb_obj.item.label.value;
                const all_regimes = source.data['regime'];
                const same_regime = [];
                for (let i = 0; i < all_regimes.length; i++) {
                    if (all_regimes[i] === regime) { same_regime.push(i); }
                }
                source.selected.indices = same_regime;
                """,
            )
        )
        plot.grid.grid_line_alpha = 0.3

        # Side panel: glossary switch, numbers, reading note
        glossary_checkbox = CheckboxGroup(
            labels=["What do the regimes mean?"], active=[],
            stylesheets=[self.accessibility_stylesheet],
            width=SIDE_PANEL_WIDTH - 20,
            margin=(30, 0, 10, 20),  # 30px top margin offsets the plot title height to align with the top gridline
        )
        summary = self._div(text=scatter_summary_html(frame), **SIDE_TEXT_LAYOUT)
        glossary = self._div(
            text=regime_glossary_html(self.accessibility["color_blind"]), visible=False, **SIDE_TEXT_LAYOUT
        )
        note = self._div(text=f"<div style='font-size:13px;'>{SCATTER_NOTE_HTML}</div>",
                         **SIDE_TEXT_LAYOUT)

        def on_glossary_change(attr, old, new):
            """Only one long text at a time: the reading note hides while the glossary is open."""
            glossary.visible = bool(new)
            note.visible = not new

        glossary_checkbox.on_change("active", on_glossary_change)
        # The glossary symbols follow the global colour-blind mode, like the markers
        self._color_blind_listeners.append(
            lambda color_blind: setattr(glossary, "text", regime_glossary_html(color_blind))
        )

        side_panel = column(glossary_checkbox, summary, glossary, note, width=SIDE_PANEL_WIDTH)
        intro = self._div(text=SCATTER_TAKEAWAY_HTML, width=FRAME_WIDTH)
        return column(self._heading(2), intro, row(plot, side_panel, width=FRAME_WIDTH), width=FRAME_WIDTH)

    # -------------------------------------------------------------------------
    # Slides 3 to 6: exceptions to the regime pattern
    # -------------------------------------------------------------------------
    def create_slide_3_regime_distribution(self):
        """Slide 3: how corrupt are the countries of each regime? (box + median bar + one dot per country)"""
        frame = self.latest_frame
        box_columns, point_columns, label_columns = build_regime_distribution(frame)
        box_source = ColumnDataSource(data=box_columns)
        point_source = self._marker_source(point_columns, point_columns["regime"], base_size=8)
        label_source = ColumnDataSource(data=label_columns)

        plot = self._figure(
            width=PLOT_WIDTH, height=520, x_range=(-0.6, 3.6), y_range=(-4, 102),
            title=f"How corrupt are the countries of each regime? ({LATEST_YEAR})",
            y_axis_label=CORRUPTION_AXIS_LABEL,
        )
        plot.xaxis.ticker = list(range(len(REGIMES)))
        plot.xaxis.major_label_overrides = dict(enumerate(box_columns["tick_label"]))
        plot.xgrid.grid_line_color = None

        # Box = middle half of the countries (interquartile range); dark bar = median. No whiskers.
        plot.vbar(x="x_position", width=0.55, bottom="q1", top="q3", source=box_source,
                  fill_color="regime_color", fill_alpha=0.25, line_color="regime_color", line_width=2)
        plot.rect(x="x_position", y="median", width=0.55, height=1.6, source=box_source,
                  fill_color="#222222", line_color="#222222")
        dots = plot.scatter(x="x_position", y="corruption_score", source=point_source, size="marker_size",
                            marker="marker_shape", fill_color="regime_color", fill_alpha=0.75,
                            line_color="outline_color", line_width="outline_width")
        plot.add_layout(self._label_set(x="x_position", y="corruption_score", text="country", source=label_source,
                                        x_offset=LABEL_OFFSET[0], y_offset=LABEL_OFFSET[1],
                                        text_font_size="12px"))
        plot.add_tools(
            HoverTool(
                renderers=[dots],
                tooltips=[("Country", "@country"), ("Regime", "@regime"),
                          ("Corruption score (100 = most corrupt)", "@corruption_score{0}"),
                          ("Continent", "@region")],
            )
        )

        scores = {regime: group for regime, group in frame.groupby("regime")["corruption_score"]}
        liberal_democracy_scores = scores["Liberal democracy"]
        electoral_democracy_scores = scores["Electoral democracy"]
        electoral_autocracy_scores = scores["Electoral autocracy"]
        closed_autocracy_scores = scores["Closed autocracy"]
        # Autocracies less corrupt than the typical electoral democracy
        electoral_democracy_median = electoral_democracy_scores.median()
        n_electoral_autocracies_cleaner = int((electoral_autocracy_scores < electoral_democracy_median).sum())
        n_closed_autocracies_cleaner = int((closed_autocracy_scores < electoral_democracy_median).sum())
        side = self._div(
            text=f"""
            <div style="font-size: 14px; color: #222; line-height: 1.6;">
                <p style="margin: 0 0 16px 0; color: #444; border-bottom: 1px solid #dde3ea; padding-bottom: 10px;">
                    <b>How to read it:</b> Each dot is a country (<b>higher = more corrupt</b>).
                    The box covers the middle 50% of countries in a regime, and the dark bar marks the median.
                </p>

                <p style="margin: 0 0 14px 0;">
                    <b>Democracies set the floor:</b><br>
                    Liberal democracies are all clean (&le; {liberal_democracy_scores.max():.0f}), while electoral democracies show wide variance ({electoral_democracy_scores.min():.0f} to {electoral_democracy_scores.max():.0f}).
                </p>

                <p style="margin: 0;">
                    <b>The regime label is not a verdict:</b><br>
                    <b>{n_electoral_autocracies_cleaner} electoral autocracies</b> (e.g. Singapore, Georgia) and <b>{n_closed_autocracies_cleaner} closed autocracies</b> score cleaner than the typical electoral democracy (median of {electoral_democracy_median:.0f}).
                </p>
            </div>
            """,
            width=SIDE_PANEL_WIDTH - 20,
            margin=(30, 0, 0, 20),  # 30px top margin offsets the plot title height to align with the top gridline
        )
        return column(self._heading(3), row(plot, side, width=FRAME_WIDTH), width=FRAME_WIDTH)

    def create_slide_4_wealth(self):
        """Slide 4: corruption score against GDP per capita (log scale), one panel per regime.
        The y label is shown only on the leftmost panels (index 0 and 2); all four panels share
        min_border_left, so the plot areas line up perfectly."""
        frame = self.latest_frame.dropna(subset=["gdp_per_capita"])
        gdp_min = frame["gdp_per_capita"].min() * 0.8
        gdp_max = frame["gdp_per_capita"].max() * 1.3
        log_gdp_min, log_gdp_max = np.log10(gdp_min), np.log10(gdp_max)
        x_range, y_range = Range1d(gdp_min, gdp_max), Range1d(0, 100)  # shared by the four panels
        stats = self.wealth_stats

        panels = []
        panel_width = FRAME_WIDTH // 2  # two panels per row = FRAME_WIDTH
        for i, (regime, color) in enumerate(REGIME_COLOR_BY_NAME.items()):
            in_regime = frame[frame["regime"] == regime]
            rank_corr = stats[regime]["rank_corr"]
            corr_text = f"rank correlation {rank_corr:+.2f}" if pd.notna(rank_corr) else "too few countries"

            panel = self._figure(
                width=panel_width, height=255, x_axis_type="log", x_range=x_range, y_range=y_range,
                title=f"{regime}: {len(in_regime)} countries, {corr_text}",
                x_axis_label="GDP per capita (log scale, $)",
                y_axis_label=CORRUPTION_AXIS_LABEL_SHORT if i % 2 == 0 else None,  # left column only
                min_border_left=65,  # same left margin on every panel, with or without the y label
            )
            if len(in_regime) >= 8:  # straight-line trend, only if there are enough countries
                slope, intercept = np.polyfit(np.log10(in_regime["gdp_per_capita"]),
                                              in_regime["corruption_score"], 1)
                trend_x = np.logspace(np.log10(in_regime["gdp_per_capita"].min()),
                                      np.log10(in_regime["gdp_per_capita"].max()), 30)
                panel.line(trend_x, slope * np.log10(trend_x) + intercept,
                           color="gray", line_dash="dashed", line_width=2)

            source = self._marker_source(
                in_regime[["gdp_per_capita", "corruption_score", "country", "deviation"]].to_dict("list"),
                [regime] * len(in_regime),
                base_size=9,
            )
            dots = panel.scatter(x="gdp_per_capita", y="corruption_score", source=source,
                                 size="marker_size", marker="marker_shape", fill_color=color, fill_alpha=0.8,
                                 line_color="outline_color", line_width="outline_width")

            # Name only the selected countries (when they belong to this regime and have GDP data).
            named = in_regime[in_regime["country"].isin(SELECTED_COUNTRIES)]
            share_of_axis = (np.log10(named["gdp_per_capita"]) - log_gdp_min) / (log_gdp_max - log_gdp_min)
            near_right_edge = share_of_axis > LABEL_FLIP_SHARE
            for subset, x_offset, align in [
                (named[~near_right_edge], 6, "left"),
                (named[near_right_edge], -6, "right"),
            ]:
                if subset.empty:
                    continue
                panel.add_layout(self._label_set(
                    x="gdp_per_capita", y="corruption_score", text="country",
                    source=ColumnDataSource(
                        data=subset[["gdp_per_capita", "corruption_score", "country"]].to_dict("list")
                    ),
                    x_offset=x_offset, y_offset=4, text_align=align, text_font_size="11px",
                ))
            panel.add_tools(HoverTool(
                renderers=[dots],
                tooltips=[("Country", "@country"), ("GDP per capita", "@gdp_per_capita{0,0}"),
                          ("Corruption score", "@corruption_score{0}"),
                          ("Distance to regime median", "@deviation{+0}")],
            ))
            panel.grid.grid_line_alpha = 0.3
            panels.append(panel)

        missing_text = "; ".join(
            f"{regime}: {s['n_missing']}" for regime, s in stats.items() if s["n_missing"] > 0
        ) or "none"

        guide = self._div(
            text=f"""
            <div style="font-size: 14px; color: #1b2a41; line-height: 1.5; margin: 0 0 12px 0;">
                <b>Key takeaway:</b> Wealthier countries tend to be cleaner across every regime (dashed trend lines slope downwards), but wealth alone does not explain the outliers.
                <div style="font-size: 12px; color: #555; margin-top: 4px;">
                    Each panel compares countries within the same regime. Countries missing due to unavailable GDP data: {missing_text}.
                </div>
            </div>
            """,
            width=FRAME_WIDTH,
        )
        return column(self._heading(4), guide, row(panels[0], panels[1], width=FRAME_WIDTH),
                      row(panels[2], panels[3], width=FRAME_WIDTH), width=FRAME_WIDTH)

    def _timeseries_panel(self, country, line, bands, width, ranges, show_y_label, show_gdp_label):
        """One small chart of slide 5: corruption score (solid line, left axis) and GDP per capita (dashed line,
        right linear axis) over a background coloured by the regime of each year."""
        x_range, y_range = ranges

        # GDP axis scaled to each country (from 0 to the country maximum)
        valid_gdp = [v for v in line["gdp_per_capita"] if pd.notna(v) and v > 0]
        max_gdp = max(valid_gdp) * 1.15 if valid_gdp else 50_000
        gdp_range = Range1d(0, max_gdp)

        panel = self._figure(
            width=width,
            height=225,
            title=country,
            x_range=x_range,
            y_range=y_range,
            min_border_left=70,
            min_border_right=75,
            extra_y_ranges={"gdp": gdp_range},
        )
        if not line["year"]:
            panel.title.text = f"{country} (no corruption score data)"
            return panel

        panel.quad(
            left="left", right="right", bottom=0, top=100, source=ColumnDataSource(data=bands),
            fill_color="regime_color", fill_alpha=0.35, line_color=None, level="underlay",
        )
        line_source = ColumnDataSource(data=line)
        curve = panel.line(x="year", y="corruption_score", source=line_source, color="#222222", line_width=2.5)
        panel.line(x="year", y="gdp_per_capita", source=line_source, y_range_name="gdp",
                   color=GDP_LINE_COLOR, line_width=2.5, line_dash="dashed")

        panel.add_tools(
            HoverTool(
                renderers=[curve],
                mode="vline",
                line_policy="nearest",
                tooltips=[("Year", "@year"), ("Corruption score", "@corruption_score{0.0}"),
                          ("GDP per capita", "@gdp_per_capita{0,0}"), ("Regime", "@regime")],
            )
        )
        panel.xaxis.ticker = [1980, 2000, 2020]
        if show_y_label:
            panel.yaxis.axis_label = CORRUPTION_AXIS_LABEL_SHORT
        panel.grid.grid_line_alpha = 0.3

        panel.add_layout(
            LinearAxis(
                y_range_name="gdp",
                axis_label="GDP per capita" if show_gdp_label else None,
                ticker=AdaptiveTicker(desired_num_ticks=4),
                formatter=NumeralTickFormatter(format="$0a"),
                axis_line_color=GDP_LINE_COLOR,
                major_tick_line_color=GDP_LINE_COLOR,
                major_label_text_color=GDP_LINE_COLOR,
                axis_label_text_color=GDP_LINE_COLOR,
            ),
            "right",
        )
        return panel

    def create_slide_5_timeseries(self):
        """Slide 5: corruption score (solid, left axis) and GDP per capita (dashed, right axis) since 1979 for the
        six selected countries, background = regime. The left label is written in the left column and the
        right label in the right column; the GDP axis is linear and scaled to each country, so read the shape of the line, not the level."""
        ranges = (Range1d(TIMESERIES_FIRST_YEAR - 0.5, LATEST_YEAR + 0.5), Range1d(0, 100))

        # Panels per row; widths add up to exactly FRAME_WIDTH (354 + 353 + 353)
        base_width, extra_pixels = divmod(FRAME_WIDTH, TIMESERIES_COLUMNS)
        column_widths = [base_width + (1 if i < extra_pixels else 0) for i in range(TIMESERIES_COLUMNS)]

        panels = []
        for i, country in enumerate(SELECTED_COUNTRIES):
            line, bands = build_timeseries(self.data, country)
            column_index = i % TIMESERIES_COLUMNS
            panels.append(self._timeseries_panel(
                country, line, bands, column_widths[column_index], ranges,
                show_y_label=(column_index == 0), show_gdp_label=(column_index == TIMESERIES_COLUMNS - 1),
            ))
        panel_rows = [
            row(*panels[start:start + TIMESERIES_COLUMNS], width=FRAME_WIDTH)
            for start in range(0, len(panels), TIMESERIES_COLUMNS)
        ]

        regime_legend = self._div(
            text="""
            <div style="font-size:12px; color:#222; margin-bottom:12px; padding:4px 0; border-top:1px solid #eef3f8; border-bottom:1px solid #eef3f8; white-space:nowrap;">
                <b>Lines:</b>
                <span style="display:inline-block; width:18px; border-top:2.5px solid #222; vertical-align:middle; margin-left:3px;"></span> Corruption (left) &nbsp;
                <span style="display:inline-block; width:18px; border-top:2.5px dashed #2b4162; vertical-align:middle;"></span> GDP (right, scaled) &nbsp;|&nbsp;
                <b>Background:</b> """
                + " &nbsp; ".join(
                    f"<span style='background:{color}; opacity:0.6; display:inline-block; width:11px; height:11px; vertical-align:middle;'></span> {regime}"
                    for regime, color in REGIME_COLOR_BY_NAME.items()
                )
                + "</div>",
            width=FRAME_WIDTH,
        )

        guide = self._div(
            text=f"""
            <div style="font-size:14px; color:#1b2a41; line-height:1.5; margin:0 0 8px 0;">
                <b>Key takeaway:</b> Political exceptions are persistent.
                <b>{self.n_persistent} of {self.n_exceptions}</b> of today's biggest outliers were already on the same side of their regime's median in {PERSISTENCE_BASE_YEAR}.
                <div style="font-size:12px; color:#555; margin-top:3px;">
                    Corruption often shifts with regime changes (background colors), while GDP growth (dashed line) rarely triggers rapid anti-corruption gains on its own.
                </div>
            </div>
            """,
            width=FRAME_WIDTH,
        )
        return column(self._heading(5), guide, regime_legend, *panel_rows, width=FRAME_WIDTH)

    def create_slide_6_conclusions(self):
        """Slide 6: clear takeaways combining conceptual points and dynamic numbers."""
        frame = self.latest_frame
        n_far_from_median = int((frame["deviation"].abs() > LARGE_DEVIATION_THRESHOLD).sum())
        share_far_from_median = n_far_from_median / len(frame)

        rank_corrs = [s["rank_corr"] for s in self.wealth_stats.values() if pd.notna(s["rank_corr"])]
        mean_rank_corr = float(np.mean(rank_corrs)) if rank_corrs else float("nan")
        n_missing_gdp = sum(s["n_missing"] for s in self.wealth_stats.values())

        content = self._div(
            text=f"""
            <div style="max-width:920px; margin:10px auto 0 auto; color:#1b2a41;">
                <div style="display:flex; flex-direction:column; gap:14px; font-size:15px; line-height:1.55;">
                    <div style="background:#f8fafc; border-left:4px solid #0072B2; padding:12px 18px; border-radius:0 6px 6px 0;">
                        <b>1. The regime sets the typical level:</b> A country's political system establishes its baseline corruption score. Across the four regimes, median scores span from <b>{frame["regime_median"].min():.0f}</b> to <b>{frame["regime_median"].max():.0f}</b>.
                    </div>

                    <div style="background:#f8fafc; border-left:4px solid #56B4E9; padding:12px 18px; border-radius:0 6px 6px 0;">
                        <b>2. Regimes overlap:</b> Political boundaries are not rigid. <b>{n_far_from_median} of {len(frame)} countries ({share_far_from_median * 100:.0f}%)</b> deviate by more than {LARGE_DEVIATION_THRESHOLD} points from their own regime's median, meaning some autocracies score cleaner than typical electoral democracies.
                    </div>

                    <div style="background:#f8fafc; border-left:4px solid #E69F00; padding:12px 18px; border-radius:0 6px 6px 0;">
                        <b>3. Wealth matters:</b> Inside a given regime, richer countries tend to be cleaner (average rank correlation: <b>{mean_rank_corr:+.2f}</b>). Wealth helps explain a portion of the exceptions, though not all.
                    </div>

                    <div style="background:#f8fafc; border-left:4px solid #D55E00; padding:12px 18px; border-radius:0 6px 6px 0;">
                        <b>4. Exceptions last:</b> The biggest exceptions are not a one-year accident: {self.n_persistent} of the {self.n_exceptions} largest outliers of {LATEST_YEAR} were already on the same side of their regime's median in {PERSISTENCE_BASE_YEAR} (e.g. Singapore).
                    </div>
                </div>

                <div style="margin-top:24px; font-size:12px; color:#5b6b7a; background:#eef3f8; padding:10px 16px; border-radius:6px; line-height:1.5;">
                    <b>Careful:</b> {n_missing_gdp} countries lack GDP data (mostly closed regimes) and are missing from slide 4. Corruption scores reflect V-Dem expert assessments. These results show statistical associations, not direct causation.
                </div>
            </div>
            """,
            width=FRAME_WIDTH,
        )
        return column(self._heading(6), content, width=FRAME_WIDTH)


# `bokeh serve` runs this file and picks up the document filled by the class
app = InteractivePresentation()